// declare global env variable to define types
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ACCOUNT_POLL_INTERVAL_MS
      ACCOUNT_WALLET_ADDRESS
      ACCOUNT_WALLET_PRIVATE_KEY
      BLOCK_POLL_INTERVAL_MS
      BLOCK_STORE_ENABLED
      DETONATIONS_KEY_EXPIRATION_SECONDS
      DETONATIONS_ENABLED
      DETONATIONS_POLL_INTERVAL_MS
      ETHEREUM_NODE_URL
      EZ_POINTS_ENABLED
      GAS_PRICE_MULTIPLIER
      GAS_PRICE_POLL_INTERVAL_MS
      GAS_PRICE_UPDATER_ENABLED
      IGNORED_MARKETS
      INITIAL_GAS_PRICE_WEI
      LEVEL_REQUESTS_ENABLED
      LEVEL_REQUESTS_KEY_EXPIRATION_SECONDS
      LEVEL_REQUESTS_POLL_INTERVAL_MS
      MINERALS_ENABLED
      NETWORK_ID
      SEQUENTIAL_TRANSACTION_DELAY_MS
      SUBGRAPH_URL
    }
  }
}

export { };
